# Generated by Django 5.1.2 on 2024-11-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='cuposLibres',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
